name: Meshery
on:
#   push:
#     branches:
#       - 'master'
#     paths-ignore:
#       - 'docs/**'
#       - 'mesheryctl/**'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - 'mesheryctl/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  err-codes:
    name: Error Codes Validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Error codes are alphabetic strings
        run: |
          badCodes=$(git diff HEAD~1 | sed -n 's/^+[^+]Err.*Code\s*=\s*"\([0-9]*\)"/\1/p' | wc -l)
          if [[ $badCodes -eq 0 ]]
          then
            echo "Test passed. All error codes are alphabetic strings"
            exit 0
          else
            echo "Test failed. $badCodes integer error codes present"
            echo "Please follow https://docs.meshery.io/project/contributing-error"
            exit 1
          fi
