name: Meshkit Error Codes Utility Runner
on:
  push:
    branches:
      - 'master'

jobs:
  Update-error-codes:
    name: Error codes utility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          #token: ${{ secrets.GH_ACCESS_TOKEN }}
          token: ${{ secrets.RELEASEDRAFTER_PAT }}

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ secrets.GO_VERSION }}

      - name: Build Error Utility
        run: |
          go build github.com/layer5io/meshkit/cmd/errorutil -o ~/errorutil

      - name: Run Utility For Meshery Server
        run: |
          ~/errorutil -d . update --skip-dirs mesheryctl
          echo '{ "errors_export": "" }' | jq --slurpfile export ./errorutil_errors_export.json '.errors_export = $export[0]' > ./docs/_data/errorref/meshery-server_errors_export.json

      - name: Run Utility For Mesheryctl
        run: |
          cd ./mesheryctl
          ~/errorutil -d . update
        # echo '{ "errors_export": "" }' | jq --slurpfile export ./errorutil_errors_export.json '.errors_export = $export[0]' > ../docs/_data/errorref/mesheryctl_errors_export.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: '--force'
          file_pattern: helpers/*.json **/*.go
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: "[Docs] Error Code Reference: update Meshery server and mehseryctl error codes"
