name: Error Reference Publisher
on:
  pull_request_review:
    types: [closed]
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'

jobs:
  error-ref:
    name: Error codes utility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ secrets.GO_VERSION }}
      - name: Error codes utility
        run: |
          go build github.com/layer5io/meshkit/cmd/errorutil
      - name: Meshery-server
        run: |
          go run github.com/layer5io/meshkit/cmd/errorutil -d . update --skip-dirs mesheryctl
          echo '{ "errors_export": '$(cat errorutil_errors_export.json)' }' | jq > docs/_data/errorref/meshery-server_errors_export.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Docs] update error reference"

