name: GraphQL API Documentation
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: 2.7.1
        bundler-cache: true
    - name: graphql-docs
      run: |
        cd docs
        bundle install
        bundle exec rake graphql:compile_docs
